### ISSUE TITLE
release new gem version

### ISSUE THREAD

**Issue by fsmanuel** [coderhs/ruby_open_weather_map#17]
Thanks for the gem. I installed it vie `gem 'open-weather'` and got `v0.10.0`.
When i added `lang: 'de'` nothing changed. The reason is that `v0.10.0` doesn't have the `lang` option.
Would be great if you cut a new release.

**Comment by coderhs** [comment]
Done, new version v0.11.0 has been released to github.

In future if you want to use the latest stable code just reference directly to the github repo

`gem 'dutch_treat', git: 'git@github.com:coderhs/ruby_open_weather_map.git'`

**Comment by fsmanuel** [comment]
@coderhs Thanks! That's what I did.

**Comment by 42races** [comment]
Use this line, there is a correction in gem name :-)

```gem 'open-weather', , git: 'git@github.com:coderhs/ruby_open_weather_map.git'```
